Add geo-related examples
turbot/steampipe-plugin-twitter pull request #11
Opened 2022-01-21 23:51 UTC by judell

# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2022-05-16 19:13 UTC, cbruno10 requested changes
Please see comments, thanks!

2022-05-16 19:13 UTC, cbruno10 commented on docs/tables/twitter_search_recent.md
> +  twitter.twitter_search_recent
```suggestion
  twitter_search_recent
```

Assuming we don't need the connection name, I think we can remove it?

2022-05-16 19:13 UTC, cbruno10 commented on docs/tables/twitter_search_recent.md
> +  twitter.twitter_search_recent
```suggestion
  twitter_search_recent
```

2022-05-16 19:13 UTC, cbruno10 commented on docs/tables/twitter_search_recent.md
> +  place ->> 'full_name',
```suggestion
  place ->> 'full_name' as place,
```

Should this column have an alias as well?

2022-05-16 23:39 UTC, judell commented
Yes to all three, thanks @cbruno10

2022-05-17 00:57 UTC, cbruno10 approved these changes

2022-05-17 00:58 UTC, merged